---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo APP_ENV is $APP_ENV && echo APP_DEBUG is $APP_DEBUG && sleep 3600"]
    env:                                  # Defines the environment variables inside the container.
    - name: APP_ENV
      valueFrom:
        configMapKeyRef:                  # Points to the example-configmap to retrieve the values for APP_ENV.
          name: example-configmap
          key: APP_ENV
    - name: APP_DEBUG
      valueFrom:                          # Points to the example-configmap to retrieve the values for APP_DEBUG.
        configMapKeyRef:
          name: example-configmap
          key: APP_DEBUG
  restartPolicy: Never
