---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-file-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "cat /config/database-config && sleep 3600"]
    volumeMounts:            # Mounts the config-volume to the /config directory inside the container.
    - name: config-volume
      mountPath: /config
  volumes:                   # The configMap key points to the example-configmap, and the items field specifies that only the database-config key should be mounted as a file named database-config in the /config directory.
  - name: config-volume
    configMap:
      name: example-configmap
      items:
      - key: database-config
        path: database-config
  restartPolicy: Never
