# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: default
subjects:
- kind: User   # Other possible values: ServiceAccount, Group
  name: jane    # Username that will get the Role's permissions
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader  # The Role to bind
  apiGroup: rbac.authorization.k8s.io
