# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""]  # "" means the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
