---
apiVersion: v1
kind: Pod
metadata:
  name: secret-file-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "cat /etc/secret-volume/username && cat /etc/secret-volume/password && sleep 3600"]
      volumeMounts:  # Mounts the secret-volume to the /etc/secret-volume directory inside the container.
        - name: secret-volume
          mountPath: /etc/secret-volume
          readOnly: true
  volumes:           # The secret key points to the db-secret, and the key-value pairs from the Secret will be available as files in the specified directory.
    - name: secret-volume
      secret:
        secretName: db-secret
  restartPolicy: Never