---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo DB_USER is $DB_USER && echo DB_PASS is $DB_PASS && sleep 3600"]
    env:                     # Defines environment variables inside the container.
    - name: DB_USER
      valueFrom:             # Points to the db-secret Secret to retrieve the values for DB_USER.
        secretKeyRef:
          name: db-secret
          key: username
    - name: DB_PASS
      valueFrom:             # Points to the db-secret Secret to retrieve the values for DB_PASS.
        secretKeyRef:
          name: db-secret
          key: password
  restartPolicy: Never
