---
apiVersion: v1             # The Secret object is part of the core Kubernetes API (v1).
kind: Secret               # Defines the object as a Secret.
metadata:                  # Provides metadata like the name of the Secret (db-secret).
  name: db-secret
type: Opaque               # Specifies the type of Secret (opaque means it holds arbitrary key-value pairs of binary or text data).
data:                      # Contains key-value pairs where the values are base64 encoded. In this case:
  username: YWRtaW4=       # Base64 encoded 'admin'
  password: cGFzc3dvcmQ=   # Base64 encoded 'password'
